status = ["clippy-check", "fmt-check", "smir-check", "purification-tests", "all-tests (ubuntu-latest)", "all-tests (windows-latest)", "all-tests (macos-latest)", "test-crates (0)", "test-crates (1)", "test-crates (2)", "test-crates (3)"]
timeout_sec = 21600
