status = ["test-crates", "clippy-check", "fmt-check", "purification-tests", "all-tests (ubuntu-latest)", "all-tests (windows-latest)", "all-tests (macos-latest)"]
timeout_sec = 21600
use_squash_merge = true
