[book]
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
language = "en"
multilingual = false
src = "src"
title = "Prusti dev guide"

[output.html.redirect]
"/config/arguments.html" = "flags.html"
