[package]
name = "prusti-contracts-build"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[build-dependencies]
prusti-utils = { path = "../prusti-utils" }
prusti-launch = { path = "../prusti-launch", artifact = "bin" }
