#![no_std]
#![allow(internal_features)]
#![cfg_attr(feature = "prusti", feature(unboxed_closures, tuple_trait))]
#![feature(core_intrinsics)]
#![feature(auto_traits)]
#![feature(negative_impls)]
#![feature(try_trait_v2)]
#![feature(cfg_version)]
#![feature(f128)]
#![feature(f16)]
#![feature(panic_internals)]
#![feature(sized_hierarchy)]

// Allow the `::prusti_contracts::` paths generated by the spec macros to
// resolve within this crate itself.
extern crate self as prusti_contracts;

// Even alloc can be disabled for consistency with std, and in preparation for future specs for other, possibly no_std, crates.
#[cfg(feature = "alloc")]
extern crate alloc;

// link to std if the feature is set
#[cfg(feature = "std")]
extern crate std;

// modules have a `_spec` suffix to avoid name conflicts with their crates.
// this is present even when compiling outside prusti to enable (negatively) implementing traits used for better specs
#[cfg(feature = "core")]
pub mod core_spec;
#[cfg(feature = "alloc")]
pub mod alloc_spec;
#[cfg(feature = "std")]
pub mod std_spec;

#[cfg(feature = "core")]
pub use core_spec::type_eq::TypeEq;

/// A macro for writing a precondition on a function.
pub use prusti_contracts_proc_macros::requires;

/// A macro for writing a postcondition on a function.
pub use prusti_contracts_proc_macros::ensures;

/// A macro for writing a pledge on a function.
pub use prusti_contracts_proc_macros::after_expiry;

/// A macro for writing a two-state pledge on a function.
pub use prusti_contracts_proc_macros::assert_on_expiry;

/// A macro for marking a function as pure.
pub use prusti_contracts_proc_macros::pure;

/// A macro for marking a function as trusted.
pub use prusti_contracts_proc_macros::trusted;

/// A macro for marking a function as opted into verification.
pub use prusti_contracts_proc_macros::verified;

/// A macro for type invariants.
pub use prusti_contracts_proc_macros::invariant;

/// A macro for writing a loop body invariant.
pub use prusti_contracts_proc_macros::body_invariant;

/// A macro for writing assertions using the full prusti specifications
pub use prusti_contracts_proc_macros::prusti_assert;

/// A macro for writing assumptions using prusti syntax
pub use prusti_contracts_proc_macros::prusti_assume;

/// A macro for writing refutations using prusti syntax
pub use prusti_contracts_proc_macros::prusti_refute;

/// A macro for impl blocks that refine trait specifications.
pub use prusti_contracts_proc_macros::refine_trait_spec;

/// A macro for specifying external functions.
pub use prusti_contracts_proc_macros::extern_spec;

/// A macro for defining a predicate using prusti expression syntax instead
/// of just Rust expressions.
pub use prusti_contracts_proc_macros::predicate;

/// Macro for creating type models.
pub use prusti_contracts_proc_macros::model;

/// A macro to add trait bounds on a generic type parameter and specifications
/// which are active only when these bounds are satisfied for a call.
pub use prusti_contracts_proc_macros::refine_spec;

/// A macro to customize how a struct or enum should be printed in a counterexample
pub use prusti_contracts_proc_macros::print_counterexample;

/// A macro to annotate termination of a function
pub use prusti_contracts_proc_macros::terminates;

/// A macro to annotate body variant of a loop to prove termination
pub use prusti_contracts_proc_macros::body_variant;

/// Definitions for compilations both with and without the `prusti` flag.
mod private_shared {
    use core::{marker::PhantomData, ops::*};
    /// A trait that allows passing in both `T` and `&T` to the functions of
    /// ghost types. This avoids the need of creating borrows everywhere for
    /// copy types.
    pub trait Value<T: ?Sized> {}
    impl<T> Value<T> for T {}
    impl<T: ?Sized> Value<T> for &T {}

    macro_rules! __dummy_from_impls__ {
        ($ty:ident: $($src:ty),*) => {$(
            impl From<$src> for $ty {
                fn from(_: $src) -> Self {
                    $ty(())
                }
            }
        )*}
    }

    macro_rules! __dummy_trait_impls__ {
        ($ty:ident: $($trait:ident $fun:ident),*) => {$(
            impl core::ops::$trait for $ty {
                type Output = Self;
                fn $fun(self, _other: Self) -> Self {
                    $ty(())
                }
            }
        )*}
    }

    /// A mathematical (unbounded) integer type.
    ///
    /// It should not be constructed by executable Rust code, hence the
    /// private unit inside.
    #[derive(Clone, Copy)]
    pub struct Int(());

    __dummy_from_impls__!(Int: i8, i16, i32, i64, i128, isize, u8, u16, u32, u64, u128, usize);
    __dummy_trait_impls__!(Int: Add add, Sub sub, Mul mul, Div div, Rem rem);

    impl Neg for Int {
        type Output = Int;
        fn neg(self) -> Self {
            Int(())
        }
    }

    /// A mathematical real number type.
    ///
    /// It should not be constructed by executable Rust code, hence the
    /// private unit inside.
    #[derive(Clone, Copy)]
    pub struct Real(());

    __dummy_from_impls__!(Real: f16, f32, f64, f128);
    __dummy_trait_impls__!(Real: Add add, Sub sub, Mul mul, Div div);

    impl Neg for Real {
        type Output = Real;
        fn neg(self) -> Self {
            Real(())
        }
    }

    // The `$d:tt` parameter must always be `$`; it is used to emit dollar
    // tokens in the nested (literal) macro definition, which is otherwise
    // impossible. See <https://stackoverflow.com/a/53971532>.
    macro_rules! __dummy_collection_impls__ {
        ($ty:ident: $macro:ident, $concat:ident, $d:tt) => {
            impl<T: ?Sized> Clone for $ty<T> {
                fn clone(&self) -> Self {
                    $ty(PhantomData)
                }
            }
            impl<T: ?Sized> Copy for $ty<T> {}
            impl<T: ?Sized> $ty<T> {
                pub fn new() -> Self {
                    $ty(PhantomData)
                }
                pub fn single(_: impl Value<T>) -> Self {
                    $ty(PhantomData)
                }
                pub fn single_ref(_: &T) -> Self {
                    $ty(PhantomData)
                }
                pub fn $concat(self, _: Self) -> Self {
                    $ty(PhantomData)
                }
                pub fn len(self) -> Int {
                    Int(())
                }
            }

            #[macro_export]
            macro_rules! $macro {
                () => {
                    $crate::$ty::new()
                };
                ($d first:expr $d(, $d rest:expr)*) => {
                    $crate::$ty::single_ref(&$d first)$d(.$concat($crate::$ty::single_ref(&$d rest)))*
                };
            }
        }
    }

    /// A mathematical sequence type, usable only in specifications and ghost
    /// code (aside from being passed around as an opaque value).
    ///
    /// All values are `Copy` and operations are functional: "modifications"
    /// like [`Seq::update`] return a new sequence. The [`seq!`](crate::seq)
    /// macro provides a convenience literal constructor.
    pub struct Seq<T: ?Sized>(PhantomData<T>);

    __dummy_collection_impls__!(Seq: seq, append, $);

    impl<T: ?Sized> Seq<T> {
        pub fn update<I>(self, _: I, _: impl Value<T>) -> Self
        where
            Int: From<I>,
        {
            Seq(PhantomData)
        }
    }

    impl<I, T: ?Sized> Index<I> for Seq<T>
    where
        Int: From<I>,
    {
        type Output = Ghost<T>;
        fn index(&self, _: I) -> &Self::Output {
            &Ghost(PhantomData)
        }
    }

    impl<I, T: ?Sized> Index<Range<I>> for Seq<T>
    where
        Int: From<I>,
    {
        type Output = Seq<T>;
        fn index(&self, _: Range<I>) -> &Self::Output {
            &Seq(PhantomData)
        }
    }

    impl<I, T: ?Sized> Index<RangeFrom<I>> for Seq<T>
    where
        Int: From<I>,
    {
        type Output = Seq<T>;
        fn index(&self, _: RangeFrom<I>) -> &Self::Output {
            &Seq(PhantomData)
        }
    }

    impl<I, T: ?Sized> Index<RangeTo<I>> for Seq<T>
    where
        Int: From<I>,
    {
        type Output = Seq<T>;
        fn index(&self, _: RangeTo<I>) -> &Self::Output {
            &Seq(PhantomData)
        }
    }

    /// A mathematical set type, usable only in specifications and ghost code
    /// (aside from being passed around as an opaque value).
    ///
    /// All values are `Copy` and operations are functional: "modifications"
    /// like [`Set::union`] return a new set. The [`set!`](crate::set) macro
    /// provides a convenience literal constructor.
    pub struct Set<T: ?Sized>(PhantomData<T>);

    __dummy_collection_impls__!(Set: set, union, $);

    impl<T: ?Sized> Set<T> {
        pub fn intersection(self, _: Self) -> Self {
            Set(PhantomData)
        }
        pub fn difference(self, _: Self) -> Self {
            Set(PhantomData)
        }
    }

    /// A mathematical multiset type, usable only in specifications and ghost
    /// code (aside from being passed around as an opaque value).
    ///
    /// All values are `Copy` and operations are functional: "modifications"
    /// like [`Multiset::union`] return a new multiset. The
    /// [`multiset!`](crate::multiset) macro provides a convenience literal
    /// constructor.
    pub struct Multiset<T: ?Sized>(PhantomData<T>);

    __dummy_collection_impls__!(Multiset: multiset, union, $);

    impl<T: ?Sized> Multiset<T> {
        pub fn intersection(self, _: Self) -> Self {
            Multiset(PhantomData)
        }
        pub fn difference(self, _: Self) -> Self {
            Multiset(PhantomData)
        }
        pub fn contains(self, _: impl Value<T>) -> Int {
            Int(())
        }
    }

    /// A mathematical map type, usable only in specifications and ghost code
    /// (aside from being passed around as an opaque value).
    ///
    /// All values are `Copy` and operations are functional: "modifications"
    /// like [`Map::insert`] return a new map. The [`map!`](crate::map) macro
    /// provides a convenience literal constructor.
    pub struct Map<K: ?Sized, V: ?Sized>(PhantomData<K>, PhantomData<V>);

    impl<K: ?Sized, V: ?Sized> Clone for Map<K, V> {
        fn clone(&self) -> Self {
            Map(PhantomData, PhantomData)
        }
    }
    impl<K: ?Sized, V: ?Sized> Copy for Map<K, V> {}

    impl<K: ?Sized, V: ?Sized> Map<K, V> {
        pub fn new() -> Self {
            Map(PhantomData, PhantomData)
        }
        pub fn insert(self, _key: impl Value<K>, _val: impl Value<V>) -> Self {
            Map(PhantomData, PhantomData)
        }
        pub fn len(self) -> Int {
            Int(())
        }
        pub fn keys(self) -> Set<K> {
            Set(PhantomData)
        }
        pub fn values(self) -> Set<V> {
            Set(PhantomData)
        }
        pub fn setminus(self, _keys: Set<K>) -> Self {
            Map(PhantomData, PhantomData)
        }
    }

    #[macro_export]
    macro_rules! map {
        ($($key:expr => $val:expr),*) => {
            $crate::map!($crate::Map::new(), $($key => $val),*)
        };
        ($existing_map:expr, $($key:expr => $val:expr),*) => {
            $existing_map
            $(
                .insert($key, $val)
            )*
        };
    }

    impl<I: Value<K>, K: ?Sized, V: ?Sized> core::ops::Index<I> for Map<K, V> {
        type Output = Ghost<V>;
        fn index(&self, _key: I) -> &Self::Output {
            &Ghost(PhantomData)
        }
    }

    /// A type holding the snapshot of a value of type `T`, usable only in
    /// specifications and ghost code (aside from being passed around as an
    /// opaque value). Produced by e.g. `ghost!` blocks and collection
    /// indexing; the wrapped value can be recovered in specifications by
    /// dereferencing.
    pub struct Ghost<T: ?Sized>(PhantomData<T>);

    impl<T: ?Sized> Clone for Ghost<T> {
        fn clone(&self) -> Self {
            Ghost(PhantomData)
        }
    }
    impl<T: ?Sized> Copy for Ghost<T> {}

    impl<T: ?Sized> Ghost<T> {
        pub fn new(_: impl Value<T>) -> Self {
            Ghost(PhantomData)
        }
        pub fn new_ref(_: &T) -> Self {
            Ghost(PhantomData)
        }
    }

    /// Ghost block. Only emitted by the `ghost!` macro, in dead code: `_body`
    /// is the ghost body inline (encoded for verification, never executed nor
    /// codegened), while `_closure` duplicates it into a never-called `Fn`
    /// closure purely so the compiler checks the body complies with `Fn`
    /// capture rules (no mutation or consumption of outer variables).
    #[doc(hidden)]
    pub fn ghost_call<T, F: Fn() -> T>(_closure: &F, _body: T) -> Ghost<T> {
        Ghost(PhantomData)
    }

    /// The runtime stand-in for a ghost block: constructs the `Ghost` ZST
    /// without evaluating anything. Only emitted by the `ghost!` macro, on
    /// the live path; its result type is inferred through the `if`/`else`
    /// from the dead [`ghost_call`] arm.
    #[doc(hidden)]
    pub fn ghost_erased<T: ?Sized>() -> Ghost<T> {
        Ghost(PhantomData)
    }
}

#[cfg(not(feature = "prusti"))]
mod private {
    pub use super::private_shared::*;

    /// A macro for defining a closure with a specification.
    /// Note: this is a declarative macro defined in this crate
    /// because declarative macros can't be exported from
    /// the `prusti-contracts-proc-macros` proc-macro crate.
    /// See <https://github.com/rust-lang/rust/issues/40090>.
    #[macro_export]
    macro_rules! closure {
        ($condition:ident ($($args:tt)*), $($tail:tt)*) => {
            $crate::closure!($($tail)*)
        };
        ($($tail:tt)*) => {
            $($tail)*
        };
    }

    /// A macro for defining ghost blocks which will be left in for
    /// verification but omitted during compilation. This mirrors the
    /// expansion under the `prusti` feature (minus the `prusti::` tool
    /// attributes): the body is only type-checked, in dead code, so that
    /// `let x = ghost! { .. }` still binds a `Ghost<T>` of the body's type.
    /// Note: this is a declarative macro defined in this crate
    /// because declarative macros can't be exported from
    /// the `prusti-contracts-proc-macros` proc-macro crate.
    /// See <https://github.com/rust-lang/rust/issues/40090>.
    #[macro_export]
    macro_rules! ghost {
        ($($body:tt)*) => {
            if false {
                $crate::ghost_call(&|| { $($body)* }, { $($body)* })
            } else {
                $crate::ghost_erased()
            }
        };
    }

    #[macro_export]
    macro_rules! prusti_assert_eq {
        ($left:expr, $right:expr $(,)?) => {};
    }

    #[macro_export]
    macro_rules! prusti_assert_ne {
        ($left:expr, $right:expr $(,)?) => {};
    }
}

#[cfg(feature = "prusti")]
mod private {
    use core::{cmp::Ordering, ops::Deref};

    /// A macro for defining a closure with a specification.
    pub use prusti_contracts_proc_macros::{closure, pure};

    /// A macro for defining ghost blocks which will be left in for
    /// verification but omitted during compilation.
    pub use prusti_contracts_proc_macros::ghost;

    pub use super::private_shared::*;

    // Generated by prusti macros, so does not need to be defined in the non-prusti case.
    #[pure]
    #[doc(hidden)]
    pub fn prusti_terminates_trusted() -> Int {
        Int::from(1)
    }

    #[macro_export]
    macro_rules! prusti_assert_eq {
        ($left:expr, $right:expr $(,)?) => {
            $crate::prusti_assert!(
                $crate::Ghost::new_ref(&($left)) == $crate::Ghost::new_ref(&($right))
            )
        };
    }

    #[macro_export]
    macro_rules! prusti_assert_ne {
        ($left:expr, $right:expr $(,)?) => {
            $crate::prusti_assert!(
                $crate::Ghost::new_ref(&($left)) != $crate::Ghost::new_ref(&($right))
            )
        };
    }

    // It should not be possible to get useful values (e.g. bool) in impure code
    // from these types (pure code is erased).
    // Note: `PartialEq` on all ghost types is *snapshot* equality of the
    // entire value, even if the element type implements `PartialEq`
    // differently: `seq![a] == seq![b]` does not invoke
    // `PartialEq::eq(&a, &b)` but compares the snapshots of `a` and `b`.

    // Int

    impl PartialEq for Int {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl Eq for Int {}

    impl PartialOrd for Int {
        fn partial_cmp(&self, _: &Self) -> Option<Ordering> {
            panic!()
        }
    }
    impl Ord for Int {
        fn cmp(&self, _: &Self) -> Ordering {
            panic!()
        }
    }

    // Real

    impl PartialEq for Real {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl Eq for Real {}

    impl PartialOrd for Real {
        fn partial_cmp(&self, _: &Self) -> Option<Ordering> {
            panic!()
        }
    }
    impl Ord for Real {
        fn cmp(&self, _: &Self) -> Ordering {
            panic!()
        }
    }

    // Seq

    /// Snapshot equality (see the note above).
    impl<T: ?Sized> PartialEq for Seq<T> {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl<T: ?Sized> Eq for Seq<T> {}

    impl<T: ?Sized> Seq<T> {
        pub fn contains(self, _: impl Value<T>) -> bool {
            panic!()
        }
    }

    // Set

    /// Snapshot equality (see the note above).
    impl<T: ?Sized> PartialEq for Set<T> {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl<T: ?Sized> Eq for Set<T> {}

    impl<T: ?Sized> Set<T> {
        pub fn is_subset(self, _: Self) -> bool {
            panic!()
        }
        pub fn contains(self, _: impl Value<T>) -> bool {
            panic!()
        }
    }

    // Multiset

    /// Snapshot equality (see the note above).
    impl<T: ?Sized> PartialEq for Multiset<T> {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl<T: ?Sized> Eq for Multiset<T> {}

    impl<T: ?Sized> Multiset<T> {
        pub fn is_subset(self, _: Self) -> bool {
            panic!()
        }
    }

    // Map

    /// Snapshot equality (see the note above).
    impl<K: ?Sized, V: ?Sized> PartialEq for Map<K, V> {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl<K: ?Sized, V: ?Sized> Eq for Map<K, V> {}

    impl<K: ?Sized, V: ?Sized> Map<K, V> {
        pub fn contains(self, _: impl Value<K>) -> bool {
            panic!()
        }
    }

    // Ghost

    /// Snapshot equality (see the note above).
    impl<T: ?Sized> PartialEq for Ghost<T> {
        fn eq(&self, _: &Self) -> bool {
            panic!()
        }
    }
    impl<T: ?Sized> Eq for Ghost<T> {}

    impl<T: ?Sized> Deref for Ghost<T> {
        type Target = T;
        fn deref(&self) -> &T {
            panic!()
        }
    }
}

/// This function is used to mark the beginning of evaluation of expressions
/// in the "before expiration" context, just before the expiry of the borrow
/// that the pledge is specifying.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn before_expiry_start() {
    panic!()
}

/// End of the context started with `before_expiry_start`.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn before_expiry_end() {
    panic!()
}

/// This function is used to mark the beginning of evaluation of expressions
/// in the "old" context, that is at the beginning of the method call.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn old_start() {
    panic!()
}

/// End of the context started with `old_start`.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn old_end() {
    panic!()
}

/// This function is used to mark the beginning of evaluation of expressions
/// in a given execution, when specifying a hyperproperty concerning multiple
/// exeuctions.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn rel_start<const E: usize>() {
    panic!()
}

/// End of the context started with `rel_start`.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn rel_end<const E: usize>() {
    panic!()
}

/// Universal quantifier.
///
/// This is a Prusti-internal representation of the `forall` syntax.
#[cfg(feature = "prusti")]
pub fn forall<T, A: core::marker::Tuple, F: Fn<A, Output = bool>>(
    _trigger_set: T,
    _closure: &F,
) -> bool {
    panic!()
}

/// Existential quantifier.
///
/// This is a Prusti-internal representation of the `exists` syntax.
#[cfg(feature = "prusti")]
pub fn exists<T, A: core::marker::Tuple, F: Fn<A, Output = bool>>(
    _trigger_set: T,
    _closure: &F,
) -> bool {
    panic!()
}

/// Specification block.
///
/// This is a Prusti-internal representation of `prusti_assert!` and others.
#[cfg(feature = "prusti")]
#[doc(hidden)]
pub fn spec_block<A: core::marker::Tuple, F: Fn<A, Output = bool>>(_closure: &F) {
    panic!()
}

/// Prusti-internal: use `f16::is_nan` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f16_is_nan(fl: f16) -> bool {
    fl.is_nan()
}

/// Prusti-internal: use `f32::is_nan` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f32_is_nan(fl: f32) -> bool {
    fl.is_nan()
}

/// Prusti-internal: use `f64::is_nan` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f64_is_nan(fl: f64) -> bool {
    fl.is_nan()
}

/// Prusti-internal: use `f128::is_nan` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f128_is_nan(fl: f128) -> bool {
    fl.is_nan()
}

/// Prusti-internal: use `f16::is_infinite` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f16_is_infinite(fl: f16) -> bool {
    fl.is_infinite()
}

/// Prusti-internal: use `f32::is_infinite` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f32_is_infinite(fl: f32) -> bool {
    fl.is_infinite()
}

/// Prusti-internal: use `f64::is_infinite` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f64_is_infinite(fl: f64) -> bool {
    fl.is_infinite()
}

/// Prusti-internal: use `f128::is_infinite` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f128_is_infinite(fl: f128) -> bool {
    fl.is_infinite()
}

/// Prusti-internal: use `f16::abs` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f16_abs(fl: f16) -> f16 {
    fl.abs()
}

/// Prusti-internal: use `f32::abs` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f32_abs(fl: f32) -> f32 {
    fl.abs()
}

/// Prusti-internal: use `f64::abs` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f64_abs(fl: f64) -> f64 {
    fl.abs()
}

/// Prusti-internal: use `f128::abs` instead, which is pure and can also be used in specifications.
#[doc(hidden)]
pub fn f128_abs(fl: f128) -> f128 {
    fl.abs()
}

pub use private::*;
