#!/bin/bash

info() { >&2 echo -e "[-] ${*}"; }
error() { >&2 echo -e "[!] ${*}"; }

# Get the directory in which this script is contained
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
info "Executing Cargo Prusti script located in '$DIR'"

# Produce binaries
export PRUSTI_FULL_COMPILATION=true

export RUSTC_WRAPPER="$DIR/prusti"
exec cargo build "$@"
