FROM fpoli/prusti-base:latest
MAINTAINER Vytautas Astrauskas "vastrauskas@gmail.com"

# Install SSH server.
RUN apt-get update && \
    apt-get install -y openssh-server && \
    rm -rf /var/lib/apt/lists/* && \
    echo 'AddressFamily inet' >> /etc/ssh/sshd_config
RUN mkdir /var/run/sshd
EXPOSE 22

ADD initialize /usr/local/bin/initialize-jenkins.sh
RUN chmod +x /usr/local/bin/initialize-jenkins.sh
CMD /usr/local/bin/initialize-jenkins.sh
