#!/bin/bash

RUST_VERSION=nightly-2018-06-27-x86_64-unknown-linux-gnu
COMPILER_PATH=/usr/local/rustup/toolchains/${RUST_VERSION}
PRUSTI_HOME=/usr/local/prusti
PRUSTI_DRIVER=${PRUSTI_HOME}/prusti-driver

#export RUST_BACKTRACE=1
export PRUSTI_FULL_COMPILATION=true
export RUST_LOG=info
export LD_LIBRARY_PATH=${COMPILER_PATH}/lib/:${JAVA_HOME}/jre/lib/amd64/server/:${PRUSTI_HOME}

echo "$@" >> /tmp/rustc_args.log

${PRUSTI_DRIVER} \
	-L ${COMPILER_PATH}/lib/rustlib/x86_64-unknown-linux-gnu/lib/ \
	--extern prusti_contracts=${PRUSTI_HOME}/libprusti_contracts.rlib \
	$@
