#! /bin/bash

cd "$(dirname "$0")"

for dep in \
 "prusti-utils"\
 "prusti-specs"\
 "prusti-contracts"\
 "prusti-contracts-impl"\
 "prusti-contracts-internal"
do
    ln -s "../../../../$dep" "$dep"
done
