[package]
name = "dummy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# This crate is just used to provide the needed dependencies
# for the mdbook documentation tests

[dependencies]
prusti-contracts = { path = "../../prusti-contracts/prusti-contracts/" }
