copy_module!(crate::typed::operations_internal::expression);
copy_module!(crate::typed::operations_internal::graphviz);
copy_module!(crate::typed::operations_internal::statement);
pub mod identifier;
copy_module!(crate::typed::operations_internal::predicate);
copy_module!(crate::typed::operations_internal::procedure);
copy_module!(crate::typed::operations_internal::successor);
copy_module!(crate::typed::operations_internal::ty);
copy_module!(crate::typed::operations_internal::lifetimes);
copy_module!(crate::typed::operations_internal::const_generics);
copy_module!(crate::typed::operations_internal::type_decl);
copy_module!(crate::typed::operations_internal::special_variables);
copy_module!(crate::typed::operations_internal::rvalue);
copy_module!(crate::typed::operations_internal::function);
copy_module!(crate::typed::operations_internal::constants);
copy_module!(crate::typed::operations_internal::helpers);
copy_module!(crate::typed::operations_internal::quantifiers);
pub mod position;
