copy_module!(crate::high::operations_internal::expression);
copy_module!(crate::high::operations_internal::graphviz);
copy_module!(crate::high::operations_internal::statement);
pub mod identifier;
copy_module!(crate::high::operations_internal::predicate);
copy_module!(crate::high::operations_internal::procedure);
copy_module!(crate::high::operations_internal::successor);
copy_module!(crate::high::operations_internal::ty);
copy_module!(crate::high::operations_internal::type_decl);
copy_module!(crate::high::operations_internal::special_variables);
pub mod position;
