[package]
name = "prusti-contracts-internal"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
prusti-specs = { path = "../prusti-specs" }
proc-macro2 = "1.0"
