[unstable]
bindeps = true

[registries.crates-io]
protocol = "sparse"

[build.'cfg(all(windows, target_arch="x86_64", target_env="msvc"))']
target = "x86_64-pc-windows-msvc"

[test.'cfg(all(windows, target_arch="x86_64", target_env="msvc"))']
target = "x86_64-pc-windows-msvc"
