[package]
name = "prusti-contracts-std"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2021"

[dependencies]
prusti-contracts = { path = "../prusti-contracts", version = "0.1.0" }

# Forward Prusti feature
[features]
prusti = ["prusti-contracts/prusti"]
