[package]
name = "prusti-contracts-internal"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
prusti-specs = { path = "../prusti-specs", optional = true }
proc-macro2 = { version = "1.0", optional = true }

[features]
# Are we being compiled by Prusti and should include dependency on
# prusti-specs and proc-macro2?
prusti = ["dep:prusti-specs", "dep:proc-macro2"]
