name: Publish on Crates.io

on:
  workflow_dispatch:
  push:
    branches: 'master'
    paths:
      - '.github/workflows/crates-io.yml'
      - 'prusti-contracts/**'
      - '!prusti-contracts/prusti-contracts-test/**'
  pull_request:
    branches: 'master'
    paths:
      - '.github/workflows/crates-io.yml'
      - 'prusti-contracts/**'
      - '!prusti-contracts/prusti-contracts-test/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Publish crates.io
        uses: katyo/publish-crates@v2
        with:
          path: './prusti-contracts'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          # Do dry run in PRs
          dry-run: ${{ github.event_name != 'push' }}
          # Without the delay `prusti-std` fails to be published since it doesn't
          # yet see the new version of `prusti-contracts`
          publish-delay: 1000
