name: Publish on Crates.io

on:
  workflow_dispatch:
  push:
    branches: [master, publish-crates-io]
    paths:
      - 'prusti-contracts/**'
      - '!prusti-contracts/prusti-contracts-test/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Move to prusti-contracts
        run: |
          mkdir tmp
          mv * tmp || true
          mv tmp/prusti-contracts/* .
          rm -rf tmp
      - name: Cache cargo
        uses: Swatinem/rust-cache@v1.3.0
      - name: Publish crates.io
        uses: katyo/publish-crates@v1
        with:
          # TODO: remove this
          dry-run: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
