name: Check GitHub pages

on:
  push:
    branches: [master, staging, trying]
    paths: 'docs/**'
  pull_request:
    branches: [master]
    paths: 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true

      # - name: Spellcheck
      #  uses: rojopolis/spellcheck-github-actions@0.27.0
