copy_module!(crate::high::operations_internal::constants);
copy_module!(crate::high::operations_internal::expression);
copy_module!(crate::high::operations_internal::function);
copy_module!(crate::high::operations_internal::graphviz);
copy_module!(crate::high::operations_internal::helpers);
pub mod const_generics;
pub mod identifier;
pub mod lifetimes;
pub mod position;
copy_module!(crate::high::operations_internal::predicate);
copy_module!(crate::high::operations_internal::procedure);
copy_module!(crate::high::operations_internal::rvalue);
copy_module!(crate::high::operations_internal::special_variables);
copy_module!(crate::high::operations_internal::statement);
copy_module!(crate::high::operations_internal::successor);
pub mod ty;
pub mod type_decl;
copy_module!(crate::high::operations_internal::variable);
